# Generated by Django 3.1.4 on 2021-04-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210413_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventhandler',
            name='status',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('InAction', 'InAction'), ('Finished', 'Finished')], max_length=200, null=True),
        ),
    ]
